// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type colorType string

const (
	DEFAULT colorType = "default"
	SUCCESS colorType = "success"
	DANGER  colorType = "danger"
)

const btnClasses = "px-2 py-2 flex items-center justify-center"
const defaultBtnClasses = `bg-blue-700 text-white hover:bg-blue-600 focus:ring-2 focus:ring-offset-2
focus:ring-blue-700`
const successBtnClasses = `bg-green-700 text-white hover:bg-green-600 focus:ring-2 focus:ring-offset-2
focus:ring-green-700`
const dangerBtnClasses = `bg-red-700 text-white hover:bg-red-600 focus:ring-2 focus:ring-offset-2 focus:ring-red-700`

type ButtonProps struct {
	ButtonType string
	id         string
	Color      colorType
	Loading    bool
}

func getColorClasses(color colorType) string {
	switch color {
	case SUCCESS:
		return successBtnClasses
	case DANGER:
		return dangerBtnClasses
	default:
		return defaultBtnClasses
	}
}

func Button(props ButtonProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 1)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
